### ISSUE TITLE
How long does it take to read the clock?

### ISSUE THREAD

**Issue by Napoleon-BlownApart** [ThomasHabets/monotonic_clock#4]
Hi Thomas,

  I'm looking for a way to measure elapsed times between events that occur at 40Hz +.
  So I'm wondering if you might be able to give an indication of how long it takes to read the clock (ie when taking a sample)?

Cheers,
Nap.

**Comment by ThomasHabets** [comment]
Good question. It's also not just about how long it takes to read the clock, but how much behind it is by the time you read it. That matters if you want to know in terms of the wall clock.

In short, I don't know. To just see how long it takes, call it twice and see the difference on your system.

To measure how behind it is you'll need external hardware.

You'll also need to think about (you didn't mention it, but maybe you have thought of it) how accurate you need these timestamps to be. Do you need microsecond accuracy? Nanosecond accuracy? If only millisecond accuracy then I don't think you need to worry at all.

**Comment by Napoleon-BlownApart** [comment]
Thank you, much appreciated comments.

I've been using gettimeofday(), but apparently the time it takes to retrieve its result is comparable to the execution time of the event handler in which I'm taking samples (in the microsecond range).

In my application, I am making measurements across processes (which include threads), and am now working on alternative strategy (and found your library in the process).

Cheers,
Nap

**Comment by ThomasHabets** [comment]
Depending on what you're doing you may want to use the RDTSC instruction. That should be the fastest and highest resolution one. It may not be stable across cores (depends on your hardware. For intel this has changed IIRC), so make sure the thread can only schedule on one CPU core.

**Comment by Napoleon-BlownApart** [comment]
I will have a read about it.  I have a middleware based on shared memory that I can use to help synchronise across processes.
The platform I'm working on is a 2014 Macbook Pro, dual booted with Ubuntu 14.04.

**Comment by sitsofe** [comment]
I think this is best answered by the links in http://stackoverflow.com/questions/16740014/computing-time-in-linux-granularity-and-precision (speficially the answers in http://stackoverflow.com/questions/6498972/faster-equivalent-of-gettimeofday where one answer includes a benchmark) so perhaps this issue can be closed?

(40Hz is still in the milisecond range but if you need nanosecond accuracy for some reason http://stackoverflow.com/a/12643656/4513656 says you need external hardware)

**Comment by Napoleon-BlownApart** [comment]
Thanks guys, after studying how Thomas implement his library, I used feature macros to allow me to have a fallback strategy with the following priorities: clock_gettime(CLOCK_MONOTONIC_RAW) >> clock_gettime(CLOCK_MONOTONIC) >> gettimeofday().  It did the trick for what I needed.

sitsofe, thanks for posting the links, I had a quick look at them and they will help me in the future I'm sure.
